theme: minima
title: Ankit Maloo
author:
  name: Ankit Maloo
  email: ankit@clioapp.ai

description: > 
  Welcome to my personal site. Still finding my way around here, so some stuff may look out of place. 


